/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 1
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 7
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_template = 3,
  anon_sym_slot = 4,
  anon_sym_block = 5,
  anon_sym_wxs = 6,
  anon_sym_SLASH_GT = 7,
  anon_sym_LT_SLASH = 8,
  anon_sym_EQ = 9,
  sym_attribute_name = 10,
  sym_attribute_value = 11,
  sym_entity = 12,
  anon_sym_SQUOTE = 13,
  aux_sym_quoted_attribute_value_token1 = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_quoted_attribute_value_token2 = 16,
  sym_text = 17,
  aux_sym__interpolation_text_token1 = 18,
  anon_sym_import = 19,
  anon_sym_include = 20,
  sym__start_tag_name = 21,
  sym__end_tag_name = 22,
  sym_raw_text = 23,
  sym_comment = 24,
  sym__interpolation_start = 25,
  sym__interpolation_end = 26,
  sym_document = 27,
  sym__node = 28,
  sym_element = 29,
  sym_start_tag = 30,
  sym_self_closing_tag = 31,
  sym_end_tag = 32,
  sym_attribute = 33,
  sym_quoted_attribute_value = 34,
  sym_interpolation = 35,
  aux_sym__interpolation_text = 36,
  sym_import_statement = 37,
  sym_include_statement = 38,
  sym_template_element = 39,
  sym_template_start_tag = 40,
  sym_template_end_tag = 41,
  sym_slot_element = 42,
  sym_slot_start_tag = 43,
  sym_slot_end_tag = 44,
  sym_block_element = 45,
  sym_wxs_element = 46,
  sym_block_start_tag = 47,
  sym_block_end_tag = 48,
  sym_wxs_start_tag = 49,
  sym_wxs_end_tag = 50,
  aux_sym_document_repeat1 = 51,
  aux_sym_start_tag_repeat1 = 52,
  aux_sym_quoted_attribute_value_repeat1 = 53,
  aux_sym_quoted_attribute_value_repeat2 = 54,
  alias_sym_expression = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_template] = "tag_name",
  [anon_sym_slot] = "tag_name",
  [anon_sym_block] = "tag_name",
  [anon_sym_wxs] = "tag_name",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_entity] = "entity",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "quoted_attribute_value_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "quoted_attribute_value_token2",
  [sym_text] = "text",
  [aux_sym__interpolation_text_token1] = "_interpolation_text_token1",
  [anon_sym_import] = "tag_name",
  [anon_sym_include] = "tag_name",
  [sym__start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym__interpolation_start] = "_interpolation_start",
  [sym__interpolation_end] = "_interpolation_end",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_interpolation] = "interpolation",
  [aux_sym__interpolation_text] = "_interpolation_text",
  [sym_import_statement] = "import_statement",
  [sym_include_statement] = "include_statement",
  [sym_template_element] = "template_element",
  [sym_template_start_tag] = "template_start_tag",
  [sym_template_end_tag] = "template_end_tag",
  [sym_slot_element] = "slot_element",
  [sym_slot_start_tag] = "slot_start_tag",
  [sym_slot_end_tag] = "slot_end_tag",
  [sym_block_element] = "block_element",
  [sym_wxs_element] = "wxs_element",
  [sym_block_start_tag] = "block_start_tag",
  [sym_block_end_tag] = "block_end_tag",
  [sym_wxs_start_tag] = "wxs_start_tag",
  [sym_wxs_end_tag] = "wxs_end_tag",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_quoted_attribute_value_repeat1] = "quoted_attribute_value_repeat1",
  [aux_sym_quoted_attribute_value_repeat2] = "quoted_attribute_value_repeat2",
  [alias_sym_expression] = "expression",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_template] = sym__start_tag_name,
  [anon_sym_slot] = sym__start_tag_name,
  [anon_sym_block] = sym__start_tag_name,
  [anon_sym_wxs] = sym__start_tag_name,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_entity] = sym_entity,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = aux_sym_quoted_attribute_value_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = aux_sym_quoted_attribute_value_token2,
  [sym_text] = sym_text,
  [aux_sym__interpolation_text_token1] = aux_sym__interpolation_text_token1,
  [anon_sym_import] = sym__start_tag_name,
  [anon_sym_include] = sym__start_tag_name,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym__interpolation_start] = sym__interpolation_start,
  [sym__interpolation_end] = sym__interpolation_end,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_interpolation] = sym_interpolation,
  [aux_sym__interpolation_text] = aux_sym__interpolation_text,
  [sym_import_statement] = sym_import_statement,
  [sym_include_statement] = sym_include_statement,
  [sym_template_element] = sym_template_element,
  [sym_template_start_tag] = sym_template_start_tag,
  [sym_template_end_tag] = sym_template_end_tag,
  [sym_slot_element] = sym_slot_element,
  [sym_slot_start_tag] = sym_slot_start_tag,
  [sym_slot_end_tag] = sym_slot_end_tag,
  [sym_block_element] = sym_block_element,
  [sym_wxs_element] = sym_wxs_element,
  [sym_block_start_tag] = sym_block_start_tag,
  [sym_block_end_tag] = sym_block_end_tag,
  [sym_wxs_start_tag] = sym_wxs_start_tag,
  [sym_wxs_end_tag] = sym_wxs_end_tag,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_quoted_attribute_value_repeat1] = aux_sym_quoted_attribute_value_repeat1,
  [aux_sym_quoted_attribute_value_repeat2] = aux_sym_quoted_attribute_value_repeat2,
  [alias_sym_expression] = alias_sym_expression,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_template] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_slot] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_wxs] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__interpolation_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__interpolation_start] = {
    .visible = false,
    .named = true,
  },
  [sym__interpolation_end] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__interpolation_text] = {
    .visible = false,
    .named = false,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_include_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_template_element] = {
    .visible = true,
    .named = true,
  },
  [sym_template_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_template_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_element] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_block_element] = {
    .visible = true,
    .named = true,
  },
  [sym_wxs_element] = {
    .visible = true,
    .named = true,
  },
  [sym_block_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_block_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_wxs_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_wxs_end_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_expression] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_expression,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__interpolation_text, 2,
    aux_sym__interpolation_text,
    alias_sym_expression,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 49,
  [65] = 50,
  [66] = 49,
  [67] = 50,
  [68] = 49,
  [69] = 50,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 21,
  [74] = 74,
  [75] = 19,
  [76] = 19,
  [77] = 77,
  [78] = 21,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 21,
  [86] = 86,
  [87] = 19,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 93,
        '&', 3,
        '\'', 90,
        '/', 6,
        '<', 39,
        '=', 47,
        '>', 40,
        'b', 15,
        'i', 19,
        's', 18,
        't', 11,
        'w', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(93);
      if (lookahead == '&') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(95);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(93);
      if (lookahead == '\'') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(49);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(92);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(47);
      if (lookahead == '>') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 14:
      if (lookahead == 'k') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(25);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(98);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 32:
      if (lookahead == 'x') ADVANCE(27);
      END_STATE();
    case 33:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 34:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(96);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 36:
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '<') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(96);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(46);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_template);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_slot);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_block);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_wxs);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{') ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{') ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{') ADVANCE(95);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{') ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym__interpolation_text_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 37, .external_lex_state = 2},
  [2] = {.lex_state = 37, .external_lex_state = 2},
  [3] = {.lex_state = 37, .external_lex_state = 2},
  [4] = {.lex_state = 37, .external_lex_state = 2},
  [5] = {.lex_state = 37, .external_lex_state = 2},
  [6] = {.lex_state = 37, .external_lex_state = 2},
  [7] = {.lex_state = 37, .external_lex_state = 2},
  [8] = {.lex_state = 37, .external_lex_state = 2},
  [9] = {.lex_state = 37, .external_lex_state = 2},
  [10] = {.lex_state = 37, .external_lex_state = 2},
  [11] = {.lex_state = 37, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 37, .external_lex_state = 2},
  [14] = {.lex_state = 37, .external_lex_state = 2},
  [15] = {.lex_state = 37, .external_lex_state = 2},
  [16] = {.lex_state = 37, .external_lex_state = 2},
  [17] = {.lex_state = 37, .external_lex_state = 2},
  [18] = {.lex_state = 37, .external_lex_state = 2},
  [19] = {.lex_state = 37, .external_lex_state = 2},
  [20] = {.lex_state = 37, .external_lex_state = 2},
  [21] = {.lex_state = 37, .external_lex_state = 2},
  [22] = {.lex_state = 37, .external_lex_state = 2},
  [23] = {.lex_state = 37, .external_lex_state = 2},
  [24] = {.lex_state = 37, .external_lex_state = 2},
  [25] = {.lex_state = 37, .external_lex_state = 2},
  [26] = {.lex_state = 37, .external_lex_state = 2},
  [27] = {.lex_state = 37, .external_lex_state = 2},
  [28] = {.lex_state = 37, .external_lex_state = 2},
  [29] = {.lex_state = 37, .external_lex_state = 2},
  [30] = {.lex_state = 37, .external_lex_state = 2},
  [31] = {.lex_state = 37, .external_lex_state = 2},
  [32] = {.lex_state = 37, .external_lex_state = 2},
  [33] = {.lex_state = 37, .external_lex_state = 2},
  [34] = {.lex_state = 37, .external_lex_state = 2},
  [35] = {.lex_state = 37, .external_lex_state = 2},
  [36] = {.lex_state = 37, .external_lex_state = 2},
  [37] = {.lex_state = 4, .external_lex_state = 2},
  [38] = {.lex_state = 1, .external_lex_state = 2},
  [39] = {.lex_state = 4, .external_lex_state = 2},
  [40] = {.lex_state = 1, .external_lex_state = 2},
  [41] = {.lex_state = 4, .external_lex_state = 2},
  [42] = {.lex_state = 1, .external_lex_state = 2},
  [43] = {.lex_state = 37, .external_lex_state = 2},
  [44] = {.lex_state = 5, .external_lex_state = 4},
  [45] = {.lex_state = 37, .external_lex_state = 2},
  [46] = {.lex_state = 5, .external_lex_state = 4},
  [47] = {.lex_state = 5, .external_lex_state = 4},
  [48] = {.lex_state = 5, .external_lex_state = 4},
  [49] = {.lex_state = 36, .external_lex_state = 5},
  [50] = {.lex_state = 36, .external_lex_state = 5},
  [51] = {.lex_state = 37, .external_lex_state = 2},
  [52] = {.lex_state = 5, .external_lex_state = 4},
  [53] = {.lex_state = 5, .external_lex_state = 4},
  [54] = {.lex_state = 37, .external_lex_state = 2},
  [55] = {.lex_state = 37, .external_lex_state = 2},
  [56] = {.lex_state = 37, .external_lex_state = 2},
  [57] = {.lex_state = 5, .external_lex_state = 4},
  [58] = {.lex_state = 5, .external_lex_state = 4},
  [59] = {.lex_state = 5, .external_lex_state = 4},
  [60] = {.lex_state = 5, .external_lex_state = 4},
  [61] = {.lex_state = 36, .external_lex_state = 5},
  [62] = {.lex_state = 37, .external_lex_state = 2},
  [63] = {.lex_state = 5, .external_lex_state = 4},
  [64] = {.lex_state = 36, .external_lex_state = 5},
  [65] = {.lex_state = 36, .external_lex_state = 5},
  [66] = {.lex_state = 36, .external_lex_state = 5},
  [67] = {.lex_state = 36, .external_lex_state = 5},
  [68] = {.lex_state = 36, .external_lex_state = 5},
  [69] = {.lex_state = 36, .external_lex_state = 5},
  [70] = {.lex_state = 37, .external_lex_state = 2},
  [71] = {.lex_state = 5, .external_lex_state = 4},
  [72] = {.lex_state = 5, .external_lex_state = 4},
  [73] = {.lex_state = 4, .external_lex_state = 2},
  [74] = {.lex_state = 5, .external_lex_state = 4},
  [75] = {.lex_state = 4, .external_lex_state = 2},
  [76] = {.lex_state = 1, .external_lex_state = 2},
  [77] = {.lex_state = 2, .external_lex_state = 6},
  [78] = {.lex_state = 1, .external_lex_state = 2},
  [79] = {.lex_state = 5, .external_lex_state = 4},
  [80] = {.lex_state = 5, .external_lex_state = 4},
  [81] = {.lex_state = 5, .external_lex_state = 4},
  [82] = {.lex_state = 36, .external_lex_state = 5},
  [83] = {.lex_state = 5, .external_lex_state = 4},
  [84] = {.lex_state = 5, .external_lex_state = 4},
  [85] = {.lex_state = 36, .external_lex_state = 5},
  [86] = {.lex_state = 0, .external_lex_state = 7},
  [87] = {.lex_state = 36, .external_lex_state = 5},
  [88] = {.lex_state = 0, .external_lex_state = 6},
  [89] = {.lex_state = 0, .external_lex_state = 7},
  [90] = {.lex_state = 0, .external_lex_state = 7},
  [91] = {.lex_state = 0, .external_lex_state = 8},
  [92] = {.lex_state = 0, .external_lex_state = 6},
  [93] = {.lex_state = 0, .external_lex_state = 6},
  [94] = {.lex_state = 0, .external_lex_state = 6},
  [95] = {.lex_state = 0, .external_lex_state = 6},
  [96] = {.lex_state = 0, .external_lex_state = 6},
  [97] = {.lex_state = 0, .external_lex_state = 6},
  [98] = {.lex_state = 0, .external_lex_state = 6},
  [99] = {.lex_state = 0, .external_lex_state = 6},
  [100] = {.lex_state = 0, .external_lex_state = 6},
  [101] = {.lex_state = 0, .external_lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_template] = ACTIONS(1),
    [anon_sym_slot] = ACTIONS(1),
    [anon_sym_block] = ACTIONS(1),
    [anon_sym_wxs] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__interpolation_start] = ACTIONS(1),
    [sym__interpolation_end] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(101),
    [sym__node] = STATE(11),
    [sym_element] = STATE(11),
    [sym_start_tag] = STATE(2),
    [sym_self_closing_tag] = STATE(16),
    [sym_interpolation] = STATE(11),
    [sym_import_statement] = STATE(11),
    [sym_include_statement] = STATE(11),
    [sym_template_element] = STATE(11),
    [sym_template_start_tag] = STATE(5),
    [sym_slot_element] = STATE(11),
    [sym_slot_start_tag] = STATE(3),
    [sym_block_element] = STATE(11),
    [sym_wxs_element] = STATE(11),
    [sym_block_start_tag] = STATE(4),
    [sym_wxs_start_tag] = STATE(86),
    [aux_sym_document_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [sym_entity] = ACTIONS(9),
    [sym_text] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym__interpolation_start] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(14), 1,
      sym_end_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(17), 2,
      sym_entity,
      sym_text,
    STATE(6), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [50] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(35), 1,
      sym_slot_end_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(21), 2,
      sym_entity,
      sym_text,
    STATE(8), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [100] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(15), 1,
      sym_block_end_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(25), 2,
      sym_entity,
      sym_text,
    STATE(9), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [150] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(18), 1,
      sym_template_end_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(29), 2,
      sym_entity,
      sym_text,
    STATE(7), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [200] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(24), 1,
      sym_end_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [250] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(25), 1,
      sym_template_end_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [300] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(26), 1,
      sym_slot_end_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [350] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(27), 1,
      sym_block_end_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [400] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LT,
    ACTIONS(41), 1,
      sym__interpolation_start,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
    ACTIONS(38), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [448] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_slot_start_tag,
    STATE(4), 1,
      sym_block_start_tag,
    STATE(5), 1,
      sym_template_start_tag,
    STATE(16), 1,
      sym_self_closing_tag,
    STATE(86), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [495] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_template,
    ACTIONS(48), 1,
      anon_sym_slot,
    ACTIONS(50), 1,
      anon_sym_block,
    ACTIONS(52), 1,
      anon_sym_wxs,
    ACTIONS(54), 1,
      anon_sym_import,
    ACTIONS(56), 1,
      anon_sym_include,
    ACTIONS(58), 1,
      sym__start_tag_name,
  [520] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_LT,
    ACTIONS(60), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_LT,
    ACTIONS(64), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [548] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LT,
    ACTIONS(68), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [562] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(72), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [576] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_LT,
    ACTIONS(76), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [590] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(80), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [604] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_LT,
    ACTIONS(84), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [618] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LT,
    ACTIONS(88), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [632] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_LT,
    ACTIONS(92), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [646] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      anon_sym_LT,
    ACTIONS(96), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [660] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(100), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [674] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(104), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [688] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_LT,
    ACTIONS(108), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [702] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LT,
    ACTIONS(112), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [716] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_LT,
    ACTIONS(116), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [730] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_LT,
    ACTIONS(120), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [744] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(124), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [758] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LT,
    ACTIONS(128), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [772] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_LT,
    ACTIONS(132), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [786] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(136), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [800] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LT,
    ACTIONS(140), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_LT,
    ACTIONS(144), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [828] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_LT,
    ACTIONS(148), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [842] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_LT,
    ACTIONS(152), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [856] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym_entity,
    ACTIONS(158), 1,
      anon_sym_SQUOTE,
    ACTIONS(160), 1,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(162), 1,
      sym__interpolation_start,
    STATE(39), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat1,
  [876] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_DQUOTE,
    ACTIONS(164), 1,
      sym_entity,
    ACTIONS(166), 1,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(168), 1,
      sym__interpolation_start,
    STATE(40), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat2,
  [896] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym__interpolation_start,
    ACTIONS(170), 1,
      sym_entity,
    ACTIONS(172), 1,
      anon_sym_SQUOTE,
    ACTIONS(174), 1,
      aux_sym_quoted_attribute_value_token1,
    STATE(41), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat1,
  [916] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym__interpolation_start,
    ACTIONS(172), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      sym_entity,
    ACTIONS(178), 1,
      aux_sym_quoted_attribute_value_token2,
    STATE(42), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat2,
  [936] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_entity,
    ACTIONS(183), 1,
      anon_sym_SQUOTE,
    ACTIONS(185), 1,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(188), 1,
      sym__interpolation_start,
    STATE(41), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat1,
  [956] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym_entity,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
    ACTIONS(196), 1,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(199), 1,
      sym__interpolation_start,
    STATE(42), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat2,
  [976] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_LT,
    ACTIONS(204), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [989] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_GT,
    ACTIONS(208), 1,
      anon_sym_SLASH_GT,
    ACTIONS(210), 1,
      sym_attribute_name,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1006] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LT,
    ACTIONS(214), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1019] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_SLASH_GT,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(216), 1,
      anon_sym_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1036] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_SLASH_GT,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(218), 1,
      anon_sym_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1053] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_SLASH_GT,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(220), 1,
      anon_sym_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1070] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(224), 1,
      sym__interpolation_start,
    ACTIONS(226), 1,
      sym__interpolation_end,
    STATE(50), 1,
      aux_sym__interpolation_text,
    STATE(82), 1,
      sym_interpolation,
  [1089] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(224), 1,
      sym__interpolation_start,
    ACTIONS(228), 1,
      sym__interpolation_end,
    STATE(61), 1,
      aux_sym__interpolation_text,
    STATE(82), 1,
      sym_interpolation,
  [1108] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_LT,
    ACTIONS(232), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1121] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(234), 1,
      anon_sym_GT,
    ACTIONS(236), 1,
      anon_sym_SLASH_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1138] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_attribute_name,
    ACTIONS(238), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1153] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_LT,
    ACTIONS(245), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1166] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LT,
    ACTIONS(249), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1179] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LT,
    ACTIONS(253), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1192] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(236), 1,
      anon_sym_SLASH_GT,
    ACTIONS(255), 1,
      anon_sym_GT,
    STATE(44), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1209] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(236), 1,
      anon_sym_SLASH_GT,
    ACTIONS(257), 1,
      anon_sym_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1226] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(236), 1,
      anon_sym_SLASH_GT,
    ACTIONS(259), 1,
      anon_sym_GT,
    STATE(47), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1243] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(236), 1,
      anon_sym_SLASH_GT,
    ACTIONS(261), 1,
      anon_sym_GT,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1260] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(266), 1,
      sym__interpolation_start,
    ACTIONS(269), 1,
      sym__interpolation_end,
    STATE(61), 1,
      aux_sym__interpolation_text,
    STATE(82), 1,
      sym_interpolation,
  [1279] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_LT,
    ACTIONS(273), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1292] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_SLASH_GT,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(275), 1,
      anon_sym_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1309] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(224), 1,
      sym__interpolation_start,
    ACTIONS(277), 1,
      sym__interpolation_end,
    STATE(65), 1,
      aux_sym__interpolation_text,
    STATE(82), 1,
      sym_interpolation,
  [1328] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(224), 1,
      sym__interpolation_start,
    ACTIONS(279), 1,
      sym__interpolation_end,
    STATE(61), 1,
      aux_sym__interpolation_text,
    STATE(82), 1,
      sym_interpolation,
  [1347] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(224), 1,
      sym__interpolation_start,
    ACTIONS(281), 1,
      sym__interpolation_end,
    STATE(67), 1,
      aux_sym__interpolation_text,
    STATE(82), 1,
      sym_interpolation,
  [1366] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(224), 1,
      sym__interpolation_start,
    ACTIONS(283), 1,
      sym__interpolation_end,
    STATE(61), 1,
      aux_sym__interpolation_text,
    STATE(82), 1,
      sym_interpolation,
  [1385] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(224), 1,
      sym__interpolation_start,
    ACTIONS(285), 1,
      sym__interpolation_end,
    STATE(69), 1,
      aux_sym__interpolation_text,
    STATE(82), 1,
      sym_interpolation,
  [1404] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(224), 1,
      sym__interpolation_start,
    ACTIONS(287), 1,
      sym__interpolation_end,
    STATE(61), 1,
      aux_sym__interpolation_text,
    STATE(82), 1,
      sym_interpolation,
  [1423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_LT,
    ACTIONS(291), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1436] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(293), 1,
      anon_sym_SLASH_GT,
    STATE(79), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1450] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(295), 1,
      anon_sym_SLASH_GT,
    STATE(80), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1464] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 2,
      sym__interpolation_start,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(94), 2,
      sym_entity,
      anon_sym_SQUOTE,
  [1476] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_EQ,
    ACTIONS(297), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1488] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 2,
      sym__interpolation_start,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(86), 2,
      sym_entity,
      anon_sym_SQUOTE,
  [1500] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 2,
      sym__interpolation_start,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(86), 2,
      sym_entity,
      anon_sym_DQUOTE,
  [1512] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      sym_attribute_value,
    ACTIONS(303), 1,
      anon_sym_SQUOTE,
    ACTIONS(305), 1,
      anon_sym_DQUOTE,
    STATE(81), 1,
      sym_quoted_attribute_value,
  [1528] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 2,
      sym__interpolation_start,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(94), 2,
      sym_entity,
      anon_sym_DQUOTE,
  [1540] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(307), 1,
      anon_sym_SLASH_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1554] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_attribute_name,
    ACTIONS(309), 1,
      anon_sym_SLASH_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1568] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1577] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 3,
      sym__interpolation_start,
      sym__interpolation_end,
      aux_sym__interpolation_text_token1,
  [1586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1595] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1604] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 3,
      sym__interpolation_start,
      sym__interpolation_end,
      aux_sym__interpolation_text_token1,
  [1613] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_LT_SLASH,
    ACTIONS(321), 1,
      sym_raw_text,
    STATE(17), 1,
      sym_wxs_end_tag,
  [1626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 3,
      sym__interpolation_start,
      sym__interpolation_end,
      aux_sym__interpolation_text_token1,
  [1635] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_LT_SLASH,
    STATE(28), 1,
      sym_wxs_end_tag,
  [1645] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1661] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 2,
      sym__end_tag_name,
      anon_sym_wxs,
  [1669] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_block,
  [1676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_GT,
  [1683] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_GT,
  [1690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_wxs,
  [1697] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_template,
  [1704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_GT,
  [1711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_GT,
  [1718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_slot,
  [1725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_GT,
  [1732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 200,
  [SMALL_STATE(7)] = 250,
  [SMALL_STATE(8)] = 300,
  [SMALL_STATE(9)] = 350,
  [SMALL_STATE(10)] = 400,
  [SMALL_STATE(11)] = 448,
  [SMALL_STATE(12)] = 495,
  [SMALL_STATE(13)] = 520,
  [SMALL_STATE(14)] = 534,
  [SMALL_STATE(15)] = 548,
  [SMALL_STATE(16)] = 562,
  [SMALL_STATE(17)] = 576,
  [SMALL_STATE(18)] = 590,
  [SMALL_STATE(19)] = 604,
  [SMALL_STATE(20)] = 618,
  [SMALL_STATE(21)] = 632,
  [SMALL_STATE(22)] = 646,
  [SMALL_STATE(23)] = 660,
  [SMALL_STATE(24)] = 674,
  [SMALL_STATE(25)] = 688,
  [SMALL_STATE(26)] = 702,
  [SMALL_STATE(27)] = 716,
  [SMALL_STATE(28)] = 730,
  [SMALL_STATE(29)] = 744,
  [SMALL_STATE(30)] = 758,
  [SMALL_STATE(31)] = 772,
  [SMALL_STATE(32)] = 786,
  [SMALL_STATE(33)] = 800,
  [SMALL_STATE(34)] = 814,
  [SMALL_STATE(35)] = 828,
  [SMALL_STATE(36)] = 842,
  [SMALL_STATE(37)] = 856,
  [SMALL_STATE(38)] = 876,
  [SMALL_STATE(39)] = 896,
  [SMALL_STATE(40)] = 916,
  [SMALL_STATE(41)] = 936,
  [SMALL_STATE(42)] = 956,
  [SMALL_STATE(43)] = 976,
  [SMALL_STATE(44)] = 989,
  [SMALL_STATE(45)] = 1006,
  [SMALL_STATE(46)] = 1019,
  [SMALL_STATE(47)] = 1036,
  [SMALL_STATE(48)] = 1053,
  [SMALL_STATE(49)] = 1070,
  [SMALL_STATE(50)] = 1089,
  [SMALL_STATE(51)] = 1108,
  [SMALL_STATE(52)] = 1121,
  [SMALL_STATE(53)] = 1138,
  [SMALL_STATE(54)] = 1153,
  [SMALL_STATE(55)] = 1166,
  [SMALL_STATE(56)] = 1179,
  [SMALL_STATE(57)] = 1192,
  [SMALL_STATE(58)] = 1209,
  [SMALL_STATE(59)] = 1226,
  [SMALL_STATE(60)] = 1243,
  [SMALL_STATE(61)] = 1260,
  [SMALL_STATE(62)] = 1279,
  [SMALL_STATE(63)] = 1292,
  [SMALL_STATE(64)] = 1309,
  [SMALL_STATE(65)] = 1328,
  [SMALL_STATE(66)] = 1347,
  [SMALL_STATE(67)] = 1366,
  [SMALL_STATE(68)] = 1385,
  [SMALL_STATE(69)] = 1404,
  [SMALL_STATE(70)] = 1423,
  [SMALL_STATE(71)] = 1436,
  [SMALL_STATE(72)] = 1450,
  [SMALL_STATE(73)] = 1464,
  [SMALL_STATE(74)] = 1476,
  [SMALL_STATE(75)] = 1488,
  [SMALL_STATE(76)] = 1500,
  [SMALL_STATE(77)] = 1512,
  [SMALL_STATE(78)] = 1528,
  [SMALL_STATE(79)] = 1540,
  [SMALL_STATE(80)] = 1554,
  [SMALL_STATE(81)] = 1568,
  [SMALL_STATE(82)] = 1577,
  [SMALL_STATE(83)] = 1586,
  [SMALL_STATE(84)] = 1595,
  [SMALL_STATE(85)] = 1604,
  [SMALL_STATE(86)] = 1613,
  [SMALL_STATE(87)] = 1626,
  [SMALL_STATE(88)] = 1635,
  [SMALL_STATE(89)] = 1645,
  [SMALL_STATE(90)] = 1653,
  [SMALL_STATE(91)] = 1661,
  [SMALL_STATE(92)] = 1669,
  [SMALL_STATE(93)] = 1676,
  [SMALL_STATE(94)] = 1683,
  [SMALL_STATE(95)] = 1690,
  [SMALL_STATE(96)] = 1697,
  [SMALL_STATE(97)] = 1704,
  [SMALL_STATE(98)] = 1711,
  [SMALL_STATE(99)] = 1718,
  [SMALL_STATE(100)] = 1725,
  [SMALL_STATE(101)] = 1732,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end_tag, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end_tag, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_element, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_element, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_element, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wxs_element, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_element, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_element, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_statement, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_statement, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_element, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_element, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_element, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_element, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_element, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_element, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_element, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wxs_element, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_statement, 4, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_statement, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_end_tag, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_end_tag, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_end_tag, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_end_tag, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_element, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_element, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_end_tag, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wxs_end_tag, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [180] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [191] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(42),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(42),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(68),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_start_tag, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_tag, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_start_tag, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_start_tag, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_start_tag, 4, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_start_tag, 4, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_start_tag, 4, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_start_tag, 4, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_start_tag, 4, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_tag, 4, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [263] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0), SHIFT_REPEAT(82),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0), SHIFT_REPEAT(64),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_start_tag, 3, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_start_tag, 3, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 1, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_start_tag, 4, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_start_tag, 3, 0, 0),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [347] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__end_tag_name = 1,
  ts_external_token_SLASH_GT = 2,
  ts_external_token_raw_text = 3,
  ts_external_token_comment = 4,
  ts_external_token__interpolation_start = 5,
  ts_external_token__interpolation_end = 6,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token__interpolation_start] = sym__interpolation_start,
  [ts_external_token__interpolation_end] = sym__interpolation_end,
};

static const bool ts_external_scanner_states[9][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_start] = true,
    [ts_external_token__interpolation_end] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_start] = true,
  },
  [3] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_start] = true,
    [ts_external_token__interpolation_end] = true,
  },
  [6] = {
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_wxml_external_scanner_create(void);
void tree_sitter_wxml_external_scanner_destroy(void *);
bool tree_sitter_wxml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_wxml_external_scanner_serialize(void *, char *);
void tree_sitter_wxml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wxml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_wxml_external_scanner_create,
      tree_sitter_wxml_external_scanner_destroy,
      tree_sitter_wxml_external_scanner_scan,
      tree_sitter_wxml_external_scanner_serialize,
      tree_sitter_wxml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "wxml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
